name: "FurryBeware Development"

services:
  database:
    container_name: "database"
    image: postgres:10.21-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database

  furrybeware:
    container_name: "furrybeware"
    image: node:16
    working_dir: /data
    command: "yarn start:dev"
    ports:
      - 9101:9101
    volumes:
      - ../:/data
    depends_on:
      - postgres

  nginx:
    container_name: "nginx"
    image: nginx:1.23.0
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pgadmin
      - furrybeware
