name: "Conventional Commits"

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Commits
      uses: webiny/action-conventional-commits@v1.0.5:webiny
